export const khodamList = [
  "Raja Gombal",
  "Penidur",
  "Penggoda Mie Instan",
  "Pencuri Gorengan",
  "Penguasa TikTok",
  "Penyedot Es Teh",
  "Penjaga Kasur",
  "Penakluk Lampu Merah",
  "Pembisik Lelucon Garing",
  "Pemburu Diskon",
  "Penguasa Meme Lucu",
  "Penggemar Durian",
  "Pembawa Payung",
  "Pengendali Remote TV",
  "Penjaga Cemilan Malam",
  "Penimbun Stiker WhatsApp",
  "Penguasa Playlist Galau",
  "Tukang Ngaret",
  "Penggila Drama Korea",
  "Penyelamat Jajan Kantin",
  "Raja Gombal",
  "Penidur",
  "Penggoda Mie Instan",
  "Pencuri Gorengan",
  "Penguasa TikTok",
  "Penyedot Es Teh",
  "Penjaga Kasur",
  "Penakluk Lampu Merah",
  "Pembisik Lelucon Garing",
  "Pemburu Diskon",
  "Penguasa Meme Lucu",
  "Penggemar Durian",
  "Pembawa Payung",
  "Pengendali Remote TV",
  "Penjaga Cemilan Malam",
  "Penimbun Stiker WhatsApp",
  "Penguasa Playlist Galau",
  "Tukang Ngaret",
  "Penggila Drama Korea",
  "Penyelamat Jajan Kantin",
  "Pemecah Daging Beku",
  "Penjaga Pintu",
  "Penguasa Chat Kosong",
  "Pemakan Bakso",
  "Penghitung Bintang",
  "Penjaga Pintu Kulkas",
  "Penebar Kentut Bau",
  "Pemanah Bantal",
  "Penjual Tawa",
  "Penjaga Wi-Fi Tetangga",
  "Pembaca Novel Misteri",
  "Peminum Susu Coklat",
  "Pengorek Telinga",
  "Penjaga Kue Lebaran",
  "Pengejar Angin",
  "Penguasa Poci Teh",
  "Pembawa Sendok Ajaib",
  "Penjaga Lukisan Antik",
  "Pelompat Pagar",
  "Pembaca Kartu Tarot",
  "Penjaga Obrolan",
  "Penguasa Komentar Receh",
  "Pengisi Air Galon",
  "Pembisik Doa",
  "Penjaga Jembatan Cinta",
  "Penjelajah Mimpi",
  "Penguasa Es Krim",
  "Penata Rambut",
  "Penjaga Buku Diary",
  "Pembawa Pulpen Ajaib",
];
